name: Simple HTML/CSS Check

on:
  push:
    branches: [ "main" ]  

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Verify files exist
        run: |
          test -f index.html
          test -f style.css
          echo "✅ HTML & CSS файли на місці"
